#!/usr/bin/perl -w

# Jeff Bucklew 
# CS 433 - Perry

# Write a program that prompts the user for two numeric inputs.  
# Verify that the first input numer (N1) is less than the 
# second input number (N2) and that the difference between the 
# two number is at least 99.  Then, repeatedly ask the user to 
# guess a secret number until the user guesses the secret number. 
# Your program should pick the number at random by using the 
# magical formula int(N1 + rand N2). When the user guesses wrong, 
# the program should respond, “Too high” or “Too low.” If the user 
# enters the word quit or exit, or if the user enters a blank line, 
# the program should quit. If the user guesses correctly, the program 
# should respond "Correct!!!" and quit.

use strict;
use 5.010;

my $num_1;
my $num_2;
my $diff;

sub get_nums
{
   print "Enter a number: ";
   chomp($num_1 = <>);
   exit 0 if($num_1 =~ "quit" or $num_1 =~ "");
   
   print "Enter another number, at least 99 greater than the previous number: ";
   chomp($num_2 = <>);
   exit 0 if($num_2 =~ "quit" or $num_2 =~ "");

   $diff = $num_2 - $num_1;
   
   return $diff; 
}

sub magic_number
{
   my $magic_num = int($num_1 + rand $num_2);
   #print "Magic number: ", $magic_num, "\n";
   
   print "Guess the secret number: ";
   chomp(my $guess = <>);
   exit 0 if($guess =~ "quit" or $num_1 =~ "");
   
   if($guess > $magic_num)
   {
      print "Too high.\n";
      magic_number();
   }
   elsif($guess < $magic_num)
   {
      print "Too low.\n";
      magic_number();
   }
   elsif($guess =~ $magic_num)
   {
      print "Correct!!!\n";
   }
}

sub play
{
   if(get_nums() < 99)
   {
	    print "Numbers were not separated by at least 99. \n";
	    play();
   }
   else
   {
	    magic_number();
   }
}

play();



